sonar.projectKey=benpate_digital-dome
sonar.organization=benpate

sonar.sources=.
sonar.exclusions=**/*_test.go,meta/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.txt
