package dome

// KnownAIBots lists the User-Agent strings of known AI crawlers.
//
// Compiled by manual scans from multiple sources:
// https://ethanmarcotte.com/wrote/blockin-bots/
// https://www.cyberciti.biz/web-developer/block-openai-bard-bing-ai-crawler-bots-using-robots-txt-file/
// https://www.nytimes.com/robots.txt
// https://www.bbc.co.uk/robots.txt
// https://connect.iftas.org/library/tools-resources/web-crawlers-and-scrapers/
// https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/
var KnownAIBots = []string{

	// Bots we know about but are going to allow...
	// "FacebookBot", //

	// https://developers.google.com/crawling/docs/crawlers-fetchers/google-common-crawlers
	// "Googlebot",
	// "Googlebot-Image"
	// "Googlebot-Video"
	// "Googlebot-News"
	// "Storebot-Google"

	"Amazonbot",
	"anthropic-ai",
	"AdsBot-Google",
	"Applebot",
	"Applebot-Extended",
	"AwarioRssBot",
	"AwarioSmartBot",
	"Bytespider", // Bytespider -> Bytedance -> TikTok
	"CCBot",
	"ChatGPT",
	"ChatGPT-User",
	"Claude", // Catch-all for Claude AI
	"ClaudeBot",
	"Claude-Web",
	"cohere-ai",
	"DataForSeoBot",
	"Diffbot",
	"FacebookExternalHit",
	"FriendlyCrawler",
	"Google-CloudVertexBot",
	"Google-Extended",
	"GPTBot",
	"ImagesiftBot",
	"magpie-crawler",
	"Meta-ExternalAgent",
	"meta-externalagent",
	"NewsNow",
	"news-please",
	"OAI-SearchBot",
	"omgili",
	"omgilibot",
	"peer39_crawler",
	"PerplexityBot",
	"PetalBot",
	"Quora-Bot",
	"Scrapy",
	"TurnitinBot",
	"Twitterbot",
	"YaK",
	"Yandex",
	"YouBot",
}

// AllKnownBadBots lists the User-Agent strings of all known bad bots,
// including every entry in KnownAIBots plus a wider set of scrapers and scanners.
//
// Compiled by manual scans from multiple sources:
// https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker (MIT Licensed)
var AllKnownBadBots = append(KnownAIBots,
	"01h4x.com",
	"360Spider",
	"404checker",
	"404enemy",
	"80legs",
	"ALittle Client",
	"Aboundex",
	"Aboundexbot",
	"Acunetix",
	"AdsTxtCrawlerTP",
	"AfD-Verbotsverfahren",
	"AhrefsBot",
	"AiHitBot",
	"Aipbot",
	"Alexibot",
	"AllSubmitter",
	"Alligator",
	"AlphaBot",
	"Anarchie",
	"Anarchy99",
	"Aspiegel",
	"Asterias",
	"Atomseobot",
	"AwarioBot",
	"AwarioRssBot",
	"AwarioSmartBot",
	"BDCbot",
	"BLEXBot",
	"BackDoorBot",
	"BackStreet",
	"Backlink-Ceck",
	"BacklinkCrawler",
	"BacklinksExtendedBot",
	"Barkrowler",
	"BatchFTP",
	"Battleztar Bazinga",
	"BetaBot",
	"BlackWidow",
	"Black Hole",
	"Blackboard",
	"BlowFish",
	"Boardreader",
	"BotALot",
	"Brandprotect",
	"Brandwatch",
	"BuiltBotTough",
	"BuiltWith",
	"Bullseye",
	"BunnySlippers",
	"BuzzSumo",
	"Bytespider",
	"CATExplorador",
	"CCBot",
	"CODE87",
	"CVE-", // Proof-of-concept tools that name their CVE
	"Calculon",
	"CazoodleBot",
	"Cegbfeieh",
	"CensysInspect",
	"ChatGPT-User",
	"CheeseBot",
	"CherryPicker",
	"ChinaClaw",
	"Claritybot",
	"ClaudeBot",
	"Cliqzbot",
	"Cloud mapping",
	"Cocolyzebot",
	"Cogentbot",
	"Collector",
	"CopyRightCheck",
	"Copyscape",
	"Craftbot",
	"Crawling at Home Project",
	"CrazyWebCrawler",
	"Crescent",
	"CrunchBot",
	"CyotekWebCopy",
	"DBLBot",
	"DIIbot",
	"DTS Agent",
	"DataCha0s",
	"DatabaseDriverMysqli",
	"Digincore",
	"DigitalPebble",
	"Dirbuster",
	"Discobot",
	"Discoverybot",
	"Dispatch",
	"DittoSpyder",
	"DnBCrawler-Analytics",
	"DnyzBot",
	"DomCopBot",
	"DomainAppender",
	"DomainCrawler",
	"DomainSigmaCrawler",
	"DomainStatsBot",
	"Domains Project",
	"Dotbot",
	"Download Wonder",
	"Dragonfly",
	"ECCP/1.0",
	"EMail Siphon",
	"EMail Wolf",
	"Ebingbong",
	"EirGrabber",
	"EroCrawler",
	"Exabot",
	"Express WebPictures",
	"ExtLinksBot",
	"Extractor",
	"ExtractorPro",
	"Extreme Picture Finder",
	"EyeNetIE",
	"FHscan",
	"FemtosearchBot",
	"Fimap",
	"Firefox/7.0",
	"FlashGet",
	"Foobot",
	"Freeuploader",
	"FrontPage",
	"FyberSpider",
	"Fyrebot",
	"G-i-g-a-b-o-t",
	"GPTBot",
	"GalaxyBot",
	"GermCrawler",
	"GetRight",
	"Getintent",
	"Gigabot",
	"Go!Zilla",
	"Go-Ahead-Got-It",
	"GrapeshotCrawler",
	"GridBot",
	"HEADMasterSEO",
	"HTMLparser",
	"HTTP::Lite",
	"Haansoft",
	"HaosouSpider",
	"Havij",
	"Heritrix",
	"HonoluluBot",
	"Humanlinks",
	"HybridBot",
	"IDBTE4M",
	"IDBot",
	"IRLbot",
	"Id-search",
	"IlseBot",
	"Image Fetch",
	"Image Sucker",
	"ImagesiftBot",
	"IndeedBot",
	"Indy Library",
	"InfoNaviRobot",
	"InfoTekies",
	"Information Security Team InfraSec Scanner",
	"InfraSec Scanner",
	"Intelliseek",
	"InterGET",
	"InternetMeasurement",
	"InternetSeer",
	"Internet Ninja",
	"IstellaBot",
	"JOC Web Spider",
	"JamesBOT",
	"Jbrofuzz",
	"JennyBot",
	"JikeSpider",
	"Jorgee",
	"JustView",
	"Jyxobot",
	"Kenjin Spider",
	"Keybot Translation-Search-Machine",
	"Keyword Density",
	"Kozmosbot",
	"LNSpiderguy",
	"LWP::Simple",
	"Lanshanbot",
	"LeechFTP",
	"LeechGet",
	"LexiBot",
	"Libwhisker",
	"LieBaoFast",
	"Lightspeedsystems",
	"LinkScan",
	"LinkWalker",
	"Linkbot",
	"LinkextractorPro",
	"LinkpadBot",
	"LinksManager",
	"LinqiaMetadataDownloaderBot",
	"LinqiaRSSBot",
	"LinqiaScrapeBot",
	"Lipperhey",
	"Lipperhey Spider",
	"Litemage_walker",
	"Lmspider",
	"Ltx71",
	"MFC_Tear_Sample",
	"MIDown tool",
	"MJ12bot",
	"MQQBrowser",
	"MSFrontPage",
	"MSIE 6.", // Spoofed: Internet Explorer 6 is extinct. MSIE 7 is left alone because Microsoft Office link previews send it
	"MSIE 8.", // Spoofed: Internet Explorer 8 is extinct
	"MSIECrawler",
	"MTRobot",
	"Mail.RU_Bot",
	"Majestic-SEO",
	"Majestic12",
	"Majestic SEO",
	"MarkMonitor",
	"MarkWatch",
	"Mass Downloader",
	"Masscan",
	"Mata Hari",
	"MauiBot",
	"Mb2345Browser",
	"MeanPath Bot",
	"Meanpathbot",
	"Mediatoolkitbot",
	"MegaIndex.ru",
	"MicroMessenger",
	"Microsoft Data Access",
	"Microsoft URL Control",
	"Minefield",
	"Mister PiX",
	"Moblie Safari",
	"Mojolicious",
	"MolokaiBot",
	"Morfeus Fucking Scanner",
	"Mr.4x3",
	"Msrabot",
	"Musobot",
	"NICErsPRO",
	"NPbot",
	"Name Intelligence",
	"Nameprotect",
	"NearSite",
	"Nessus",
	"NetLyzer",
	"NetMechanic",
	"NetSpider",
	"Net Vampire",
	"Netcraft",
	"Nettrack",
	"Netvibes",
	"NextGenSearchBot",
	"Niki-bot",
	"Nikto",
	"NimbleCrawler",
	"Nimbostratus",
	"Nmap",
	"Nuclei",
	"Offline Explorer",
	"Offline Navigator",
	"OnCrawl",
	"OpenLinkProfiler",
	"OpenVAS",
	"Openfind",
	"Openvas",
	"OrangeBot",
	"OrangeSpider",
	"OutclicksBot",
	"OutfoxBot",
	"PECL::HTTP",
	"PHPCrawl",
	"POE-Component-Client-HTTP",
	"PageAnalyzer",
	"PageGrabber",
	"PageScorer",
	"PageThing.com",
	"Page Analyzer",
	"Pandalytics",
	"Panscient",
	"Papa Foto",
	"PeoplePal",
	"Petalbot",
	"Pi-Monster",
	"Picscout",
	"Picsearch",
	"PictureFinder",
	"Piepmatz",
	"Pimonster",
	"PleaseCrawl",
	"ProPowerBot",
	"ProWebWalker",
	"Probethenet",
	"Proximic",
	"Psbot",
	"PxBroker",
	"QueryN Metasearch",
	"Quick-Crawler",
	"RSSingBot",
	"Rainbot",
	"RankActive",
	"RankActiveLinkBot",
	"RankFlex",
	"RankingBot",
	"RankingBot2",
	"Rankivabot",
	"RankurBot",
	"RealDownload",
	"RebelMouse",
	"Recorder",
	"RedesScrapy",
	"RepoMonkey",
	"RocketCrawler",
	"Rogerbot",
	"SEOkicks",
	"SEOkicks-Robot",
	"SEOlyticsCrawler",
	"SEOprofiler",
	"SEOstats",
	"SMTBot",
	"SalesIntelligent",
	"ScanAlert",
	"Scanbot",
	"ScoutJet",
	"Screaming",
	"ScreenerBot",
	"ScrepyBot",
	"Searchestate",
	"SearchmetricsBot",
	"Seekport",
	"SeekportBot",
	"SemanticJuice",
	"SemrushBot",
	"SentiBot",
	"SenutoBot",
	"SeoCherryBot",
	"SeoSiteCheckup",
	"SeobilityBot",
	"Shodan",
	"SiteCheckerBotCrawler",
	"SiteExplorer",
	"SiteLockSpider",
	"SiteSnagger",
	"SiteSucker",
	"Site Sucker",
	"Sitebeam",
	"Siteimprove",
	"Sitevigil",
	"SlySearch",
	"SmartDownload",
	"Snapbot",
	"SocialRankIOBot",
	"Sociscraper",
	"Sogou web spider",
	"Sosospider",
	"Sottopop",
	"SpaceBison",
	"SpankBot",
	"Spbot",
	"Spider_Bot",
	"Spider_Bot/3.0",
	"Spinn3r",
	"SputnikBot",
	"Sqlmap",
	"Sqlworm",
	"Sqworm",
	"Stripper",
	"SuperBot",
	"SuperHTTP",
	"Surfbot",
	"SurveyBot",
	"Swiftbot",
	"T0PHackTeam",
	"T8Abot",
	"Teleport",
	"TeleportPro",
	"Telesoft",
	"Telesphoreo",
	"Telesphorep",
	"TheNomad",
	"The Intraformant",
	"TightTwatBot",
	"TinyTestBot",
	"Toweyabot",
	"Tracemyfile",
	"Trendiction",
	"Trendictionbot",
	"True_Robot",
	"Turingos",
	"Turnitin",
	"TurnitinBot",
	"TwengaBot",
	"Typhoeus",
	"URLy.Warning",
	"URLy Warning",
	"UnisterBot",
	"VB Project",
	"Vagabondo",
	"VelenPublicWebCrawler",
	"VeriCiteCrawler",
	"VidibleScraper",
	"Virusdie",
	"WASALive-Bot",
	"WBSearchBot",
	"WISENutbot",
	"WPScan",
	"WWW-Collector-E",
	"WWW-Mechanize",
	"WWW::Mechanize",
	"WWWOFFLE",
	"Wallpapers",
	"Wallpapers/3.0",
	"WallpapersHD",
	"WebBandit",
	"WebCollage",
	"WebCopier",
	"WebEnhancer",
	"WebFetch",
	"WebGo IS",
	"WebImageCollector",
	"WebLeacher",
	"WebReaper",
	"WebSauger",
	"WebStripper",
	"WebSucker",
	"WebWhacker",
	"Web Auto",
	"Web Collage",
	"Web Enhancer",
	"Web Fetch",
	"Web Fuck",
	"Web Sauger",
	"Web Sucker",
	"WebmasterWorldForumBot",
	"Webshag",
	"WebsiteExtractor",
	"WebsiteQuester",
	"Website Quester",
	"Whatweb",
	"Who.is Bot",
	"WinHTTrack",
	"WiseGuys Robot",
	"Wonderbot",
	"Woobot",
	"Wprecon",
	"Xaldon WebSpider",
	"Xaldon_WebSpider",
	"YoudaoBot",
	"Zitebot",
	"ZmEu",
	"ZoomBot",
	"ZoominfoBot",
	"ZumBot",
	"adscanner",
	"anthropic-ai",
	"archive.org_bot",
	"arquivo-web-crawler",
	"arquivo.pt",
	"autoemailspider",
	"awario.com",
	"backlink-check",
	"cah.io.community",
	"check1.exe",
	"clark-crawler",
	"coccocbot",
	"cognitiveseo",
	"cohere-ai",
	"com.plumanalytics",
	"crawl.sogou.com",
	"crawler.feedback",
	"crawler4j",
	"cve-", // Proof-of-concept tools that name their CVE: cve-2026-87902-poc/1.0
	"dataforseo.com",
	"dataforseobot",
	"demandbase-bot",
	"domainsproject.org",
	"evc-batch",
	"everyfeed-spider",
	"facebookscraper",
	"heritrix",
	"imagesift.com",
	"instabid",
	"internetVista monitor",
	"ips-agent",
	"isitwp.com",
	"iubenda-radar",
	"linkdexbot",
	"linkfluence",
	"lwp-request",
	"lwp-trivial",
	"magpie-crawler",
	"meanpathbot",
	"mediawords",
	"muhstik-scan",
	"netEstate NE Crawler",
	"oBot",
	"openai.com",
	"page scorer",
	"pcBrowser",
	"plumanalytics",
	"polaris version",
	"probe-image-size",
	"s1z.ru",
	"satoristudio.net",
	"scalaj-http",
	"scan.lol",
	"seobility",
	"seocompany.store",
	"seoscanners",
	"serpstatbot",
	"sexsearcher",
	"sitechecker.pro",
	"siteripz",
	"sogouspider",
	"sp_auditbot",
	"sysscan",
	"trendiction.com",
	"trendiction.de",
	"ubermetrics-technologies.com",
	"voyagerx.com",
	"webgains-bot",
	"webmeup-crawler",
	"webpros.com",
	"webprosbot",
	"x09Mozilla",
	"x22Mozilla",
	"xpymep1.exe",
	"zauba.io",
	"zgrab",
)
